services:
  homeassistant:
    container_name: ha-ajax-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha-config:/config
      - ./custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - "8124:8123"
